In [79]:
import numpy as np


arr1= np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [80]:
arr = np.array([1,2,3,4,5])

print(arr)
print(arr.shape)
print(arr.reshape(1,5))

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]


In [81]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)       

array([[1, 2, 3, 4, 5]])

In [82]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [83]:
range = np.arange(5,50,2)
reshape = np.arange(0,50,10).reshape(1,5)

print(range)
print("reshaped elements", reshape)


[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
reshaped elements [[ 0 10 20 30 40]]


In [84]:
np.arange(0,10,2).reshape(1,5)


array([[0, 2, 4, 6, 8]])

In [85]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [86]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [87]:
ndarray = np.array([5,1,6,6,2])
print(ndarray)

[5 1 6 6 2]


In [88]:
#  0-D,    Zero dimention array 
Zero_D_array = np.array(42)
print(Zero_D_array)


42


In [89]:
one_D_array = np.array([1,2,3,4,5])
print(one_D_array)

[1 2 3 4 5]


In [90]:
Two_D_array = np.array([[1,2,3], [4,5,6]])
print( Two_D_array)

[[1 2 3]
 [4 5 6]]


In [91]:
three_D_array= np.array([[[1,2,3], [4,5,6]], [[1,6,2], [4,3,6]]])
print(three_D_array)

[[[1 2 3]
  [4 5 6]]

 [[1 6 2]
  [4 3 6]]]


In [92]:
# ndim = for checking num dimention 

print(Zero_D_array.ndim, 'dimention')
print(one_D_array.ndim, 'dimention')
print(Two_D_array.ndim, 'dimention')
print(three_D_array.ndim, 'dimention')

0 dimention
1 dimention
2 dimention
3 dimention


In [93]:
arr = np.array((1,2,3,4), ndmin=2)
print(arr)


[[1 2 3 4]]


In [94]:
#  indexing
arr = np.array((1,2,3,4))
print(arr[0])
print(arr[2])
print(arr[2]+ arr[3])


1
3
7


In [95]:
arr = np.array([[1,2,3],[4,5,6]])

print('first row takes index zero', arr[0])
print('second row takes index one', arr[1])

print('2nd element of 1st row is ', arr[0,2])

first row takes index zero [1 2 3]
second row takes index one [4 5 6]
2nd element of 1st row is  3


In [96]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  #row 0 and row 1 

print(arr[0:2 , 0]) # slicing 0:2,  means 0 and 1 row included (and 2 exclded) with coloumn 0 element.

# The Result
# Row 0, column 0 has the value 1.
# Row 1, column 0 has the value 6

[1 6]


In [97]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])

print(arr[1,2])
print(arr[0,4])


6
5


In [98]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[1,0,2])

6
9


In [99]:
# Slicing

arr = np.array([1,2,3,4,5,6,7])

print(arr[0:3])
print(arr[:5])
print(arr[0:-3])
print(arr[-4:-1])
print(arr[0:6:2])
print(arr[::2])
print(arr[::3])

[1 2 3]
[1 2 3 4 5]
[1 2 3 4]
[4 5 6]
[1 3 5]
[1 3 5 7]
[1 4 7]


In [100]:
arr = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])

print(arr[0, 1:4])
print(arr[1, 2:5])

[2 3 4]
[6 7 8]


In [101]:
#  from both elements

arr = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])

print('row 0 :', arr[0, 1:4])
print('column 1: ', arr[0:2, 1]) # 0:2 stands for rows 0 and 1, and num 1 stands for column 1 of row
print('column 4: ', arr[0:2, 4])
print('column 1 to 4: ',arr[0:2, 1:4])

row 0 : [2 3 4]
column 1:  [2 5]
column 4:  [5 8]
column 1 to 4:  [[2 3 4]
 [5 6 7]]


In [102]:
arr = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
for x in arr:
    print(x)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [103]:
arr = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
for x in arr:
    for y in x:
        print(y)

# When you use nested loops like this, each element y gets printed one by one in sequence

1
2
3
4
5
6
4
5
6
7
8
9


In [104]:
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])

for x in arr:
    for y in x:
        print('printig 2nd loop', y)

for x in arr:
    for y in x:
        for z in y:
            print('printing 3rd loop', z)




printig 2nd loop [1 2 3]
printig 2nd loop [4 5 6]
printig 2nd loop [1 2 3]
printig 2nd loop [4 5 6]
printing 3rd loop 1
printing 3rd loop 2
printing 3rd loop 3
printing 3rd loop 4
printing 3rd loop 5
printing 3rd loop 6
printing 3rd loop 1
printing 3rd loop 2
printing 3rd loop 3
printing 3rd loop 4
printing 3rd loop 5
printing 3rd loop 6


# starting with **Pandas**

* Series -  A pandas Series is like a column of data with labels (called an index). It is a one-dimensional array 
  
  that can hold any data type.

* DataFram  -  two dimension labeled array, with multiple columns and rows, as like - excel sheet       

In [10]:
import pandas as pd


# creating a series from list

data= [1,2,3,4,5]

series= pd.Series(data)
print('series\n', series)
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [106]:
# creating a dictonary series from tuple
data= {'a': 1, 'b': 2, 'c': 3}

series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [107]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data, index=index)


a    10
b    20
c    30
dtype: int64

# DATAFRAME

In [108]:
# DATAFRAME
## create a Dataframe from a dictionary of list

data ={'Name':['Shweta', 'Shivani', 'Vamika'], 'Age': [25,30,40], 'City':['New York','Madurai','Delhi']}

df= pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age      City
0   Shweta   25  New York
1  Shivani   30   Madurai
2   Vamika   40     Delhi
<class 'pandas.core.frame.DataFrame'>


In [109]:
import numpy as np
np.array(df)

array([['Shweta', 25, 'New York'],
       ['Shivani', 30, 'Madurai'],
       ['Vamika', 40, 'Delhi']], dtype=object)

In [110]:
data = [
         {'Name':'Shweta', 'Age': 24, 'City':'New York'},
         {'Name':'Tanya', 'Age': 21, 'City':'New York'},
         {'Name':'Smita', 'Age': 27, 'City':'New York'},
         {'Name':'Minakshi', 'Age': 26, 'City':'New York'},
         ]

df = pd.DataFrame(data)

print(df)


       Name  Age      City
0    Shweta   24  New York
1     Tanya   21  New York
2     Smita   27  New York
3  Minakshi   26  New York


In [111]:
df = pd.read_csv('sales_data.csv')
print(df.head(5))


         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North


In [112]:
print(df.tail(5))

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North


In [113]:
# Accesing data from datafram   
data = [
         {'Name':'Shweta', 'Age': 24, 'City':'New York'},
         {'Name':'Tanya', 'Age': 21, 'City':'New York'},
         {'Name':'Smita', 'Age': 27, 'City':'New York'},
         {'Name':'Minakshi', 'Age': 26, 'City':'New York'},
         ]

df = pd.DataFrame(data)

df


Name  Age      City
0    Shweta   24  New York
1     Tanya   21  New York
2     Smita   27  New York
3  Minakshi   26  New York

In [114]:
df['Name']



0      Shweta
1       Tanya
2       Smita
3    Minakshi
Name: Name, dtype: object

In [115]:
type(df['Name'])

pandas.core.series.Series

In [116]:
# for row index location

df.loc[0]

Name      Shweta
Age           24
City    New York
Name: 0, dtype: object

In [117]:
# column index location

df.iloc[0]

Name      Shweta
Age           24
City    New York
Name: 0, dtype: object

In [118]:
# index location

df.iloc[0][0]



C:\Users\common\AppData\Local\Temp\ipykernel_14896\487769857.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]


'Shweta'

In [119]:
df.iloc[0][1]


C:\Users\common\AppData\Local\Temp\ipykernel_14896\4037899947.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]


24

In [120]:
df.iloc[1][0]


C:\Users\common\AppData\Local\Temp\ipykernel_14896\1154082844.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][0]


'Tanya'

In [121]:
# accesing specified element

print(df.at[1,'Age'])
print(df.at[3,'Age'])

21
26


In [122]:
print(df.at[1,'Name'])
print(df.at[2,'Name'])

Tanya
Smita


In [123]:
#  for accesing row and column both

# SYNTAX = iat[row num, column num]

df.iat[2,1]

27

# Data manupulation with Datafram



In [124]:
# Data manupulation with Datafram
data = [
         {'Name':'Shweta', 'Age': 24, 'City':'New York'},
         {'Name':'Tanya', 'Age': 21, 'City':'New York'},
         {'Name':'Smita', 'Age': 27, 'City':'New York'},
         {'Name':'Minakshi', 'Age': 26, 'City':'New York'},
         ]

df = pd.DataFrame(data)

df


Name  Age      City
0    Shweta   24  New York
1     Tanya   21  New York
2     Smita   27  New York
3  Minakshi   26  New York

In [125]:
# adding new coloumn
df['Salary']= [50000,60000,80000,30000]
df

Name  Age      City  Salary
0    Shweta   24  New York   50000
1     Tanya   21  New York   60000
2     Smita   27  New York   80000
3  Minakshi   26  New York   30000

# Removing column for temporary

In [126]:
# Removing column for temporary
# drop ke sath me axis=1 hoga for coloumn, because datafram consider row as axis=0 .

df.drop('Salary', axis=1)


Name  Age      City
0    Shweta   24  New York
1     Tanya   21  New York
2     Smita   27  New York
3  Minakshi   26  New York

In [127]:
df

Name  Age      City  Salary
0    Shweta   24  New York   50000
1     Tanya   21  New York   60000
2     Smita   27  New York   80000
3  Minakshi   26  New York   30000

# Removing column for parmanently


In [128]:
# Removing column for parmanently

df.drop('Salary', axis=1, inplace=True)
df

Name  Age      City
0    Shweta   24  New York
1     Tanya   21  New York
2     Smita   27  New York
3  Minakshi   26  New York

In [129]:
df['Age'] = df['Age'] +5
df

Name  Age      City
0    Shweta   29  New York
1     Tanya   26  New York
2     Smita   32  New York
3  Minakshi   31  New York

# **DATA MANIPULTION**

In [3]:
import pandas as pd



In [4]:
# here I add my sales csv file.

df = pd.read_csv('sales_data.csv')

df.head()

Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [132]:
df.tail(5)

Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [133]:
# it finds numerical coulmns and apply some mathematical operations on it.

df.describe()

Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [134]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

# What .any() Does

*SYNTAX - any(iterable)*

* The any() function returns:
* True if at least *one* element of the iterable is True.
* False if *all* elements are False or if the iterable is empty.

```python
values = [0, False, None, 3, '']
print(any(values))  # Output: True

In [135]:
# axis=0, showing missing values in which columns.
# axis=0, is default


print(df.isnull().any(axis=0))      # both print same output
df.isnull().any()                   # axis=0 is default value so this will appear same as upper code

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool


Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [136]:
# axis=1, showing missing values in which row
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [137]:
# showing how many values are missing in each column
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [138]:
# showing how many values are missing in each row.
df.isnull().sum(axis=1)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    1
12    0
13    0
14    0
15    1
16    0
17    1
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    1
29    0
30    0
31    0
32    0
33    1
34    0
35    1
36    0
37    1
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
dtype: int64

In [139]:
df = pd.read_csv('sales_data.csv')


print(df.head())  # by default head() shows first 5 rows, when i don't pass any argument to head() function
print(df.tail())  # by default tail() shows last 5 rows, same as head() function


         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North


In [5]:
df.describe()

Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [141]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [8]:
# It works element-wise over the DataFrame or Series and identifies missing values in all rows and columns.
# output will be in bool value.

df.isnull()

Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [9]:
#  isnull().sum() - will show the sum of null values present in each column.

df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [144]:
# any() - gives bool ouput if there is any missing value in the column.

df.isnull().any()  #as default axis=0 is taken, sum of column

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [145]:
df.isnull().any(axis=1)  #sum of row

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [146]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [147]:
df.fillna(0)

# missing value will be replaced with zero 0, or any other value you want to replace with.

Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [148]:
df['Sales_fillNA']= df['Sales'].fillna(df['Sales'].mean())

df

Date Category  Value   Product  Sales Region  Sales_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [149]:
# groupby() - will group the data by the column name
# mean() - will calculate the mean of the grouped data
df.groupby(['Product'])['Value'].mean()


Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [150]:
df.groupby(['Product', 'Region'])['Value'].mean()


Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [152]:
df.groupby(['Product', 'Region'])['Value'].sum()


Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [153]:
# created new dataset
df1 = pd.DataFrame({'key':['A','B','C'], 'Value' : [1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'], 'Value2' : [4,5,6]})


In [154]:
df1

key  Value
0   A      1
1   B      2
2   C      3

In [155]:
pd.merge(df1,df2,on='key')

# by default take 'inner' merge, and print same data set 

key  Value  Value2
0   A      1       4
1   B      2       5

In [156]:
pd.merge(df1,df2,on='key', how='inner')

key  Value  Value2
0   A      1       4
1   B      2       5

In [158]:
pd.merge(df1,df2,on='key', how='outer')
# with 'outer' it prints whole data with Nan values

key  Value  Value2
0   A    1.0     4.0
1   B    2.0     5.0
2   C    3.0     NaN
3   D    NaN     6.0

In [157]:
pd.merge(df1,df2,on='key', how='left')

key  Value  Value2
0   A      1     4.0
1   B      2     5.0
2   C      3     NaN

In [ ]:
# !pip install lxml

In [3]:
# !pip install html5lib
# !pip install beautifulsoup4

In [4]:
# !pip install openpyxl